---
title: DANL Project
subtitle: "Data-Driven Mastery: Unlocking Business Potential"
author: 
  - Jackson Boyer
  - Alban Kuka
  - Henry Socash
  - Jeremy Sun
  - Tori Pavlock

toc: true
toc-title: "Table of Contents"
toc-depth: 2
number-sections: true

fig-width: 9

execute:
  code-tools: true
  message: false
  warning: false

from: markdown+emoji
---
```{r setup}
#| include: false
library(tidyverse)
library(skimr)
library(ggthemes)
library(hrbrthemes)
library(ggplot2)


theme_set(theme_ipsum()+
          theme(strip.background =element_rect(fill="lightgray"),
                axis.title.x = 
                  element_text(angle = 0,
                               size = rel(1.33),
                               margin = margin(10,0,0,0)),
                axis.title.y = 
                  element_text(angle = 0,
                               size = rel(1.33),
                               margin = margin(0,10,0,0))
                )
          )
```



# Introduction

This is a data.frame about the earthquakes that occurred in 2023. It provides information such as latitude, longitude, where it occurred, etc. 
```{r}
eq <- read_csv('/Users/jacksonboyer/Documents/Data Analytics/Project/jbdanl.github.io/earthquake data.csv')
```


# Data

The data.frame `eq` contains data about any earthquakes that have occurred from September 1st, 2023 to October 1st, 2023. It contains data from all around the world.  


## Summary Statistics

```{r}
rmarkdown::paged_table(eq) 
```

```{r}
#| results: asis
#| echo: false
 
```


```{r}
skim(eq) %>% 
  select(-n_missing)
```


## MPG and a Type of Cars
.


```{r}
ggplot(data = mpg) +
  geom_boxplot(aes(x = class, y = hwy, fill = class),
               show.legend = F) +
  labs(x = "Class", y = "Highway\nMPG") 
```



